[versions]
activityVersion = "1.7.2"
agp = "8.11.1"
androidxJunit = "1.1.5"
appcompatVersion = "1.6.1"
constraintlayoutVersion = "2.1.4"
espressoCoreVersion = "3.5.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
materialVersion = "1.9.0"
roomRuntime = "2.6.1"
roomRxjava2 = "2.7.2"
firebaseFirestore = "26.0.0"

[libraries]
activity-v172 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "roomRxjava2" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

